### ISSUE TITLE
I think this project can be good fit for LGU open-source community

### ISSUE THREAD

**Issue by Zain-ul-din** [zxynxb/e-commerce-management-system#1]
AOA, I'm Zain-ul-din from LGU. I'm an open-source developer and creator of [LGU unofficial timetable](https://www.lgutimetable.online/). 

Some time ago, I wondered if we could build our open-source community at LGU. I couldn't find enough people to start it, but just saw your project, and it seems like you built it out of passion. Would you like to be part of the LGU open-source community, which I haven't started yet, and also transfer your project there just for showcasing?

**Comment by zxynxb** [comment]
ws, YESS i would love to tbh and sure you can transfer it there for showcasing just credit me 
im working on it in oop there's a new version coming sooon tooo!!

**Comment by Zain-ul-din** [comment]
Thank you! Perhaps I'll talk to VC tomorrow then I'll create a new org here on Git Hub do you have any name in your name what should we name it?

**Comment by zxynxb** [comment]
give me some details about the community and ill suggest a name

**Comment by Zain-ul-din** [comment]
sure! my plan is to make a Github org as it is LGU open-source community. where students can upload their projects like sem proj's or maybe personal project just for showcase. atm I've got a plan.

**Comment by zxynxb** [comment]
GARRISON CODE COMMUNITY (GCC)?

**Comment by Zain-ul-din** [comment]
sounds good! so shall we go with just GCC?

**Comment by zxynxb** [comment]
i personally think there should be a club or society in lgu where students willingly participate in making softwares mostly for university and students benefits 
lile let's suppose make a app to help preparation like notes and etc integrated with ai specifically for that

**Comment by zxynxb** [comment]
> sounds good! so shall we go with just GCC?

YESSSS IT WOULD BE SO COOL unless u want a more movie kind of name like having words like warriors/rangers lmk

**Comment by Zain-ul-din** [comment]
tbh i created too much software for students for free but NO BODY CARES especially from management. That's why I decided to go independently

**Comment by zxynxb** [comment]
LETS MAKE A COMMUNITY THEN EVERYONE WILL SEEE EVERYONE'S PROJECTS

**Comment by Zain-ul-din** [comment]
> > sounds good! so shall we go with just GCC?
> 
> YESSSS IT WOULD BE SO COOL unless u want a more movie kind of name like having words like warriors/rangers lmk

No I don't like name which sounds like movie name

**Comment by zxynxb** [comment]
OKI THEN GCC IS BEST

**Comment by Zain-ul-din** [comment]
![image](https://github.com/zxynxb/e-commerce-management-system/assets/78583049/905eae42-a131-4da9-a759-6fec1d000e77)

OOPS!

**Comment by zxynxb** [comment]
wait lemme brainstorm some more and ill let yk ;)

**Comment by zxynxb** [comment]
![Screenshot_20240526-134507](https://github.com/zxynxb/e-commerce-management-system/assets/158732374/d2937682-5bf4-415d-90ce-1ddff445b46b)
lgu code community

**Comment by Zain-ul-din** [comment]
lemme make this one.

**Comment by zxynxb** [comment]
OKIII add me tooooo!!!

**Comment by Zain-ul-din** [comment]
Here we go!

**Comment by zxynxb** [comment]
do we need to make a logo? 
i can make one

**Comment by Zain-ul-din** [comment]
yeah! why not 😄

**Comment by Zain-ul-din** [comment]
where u'll design?

**Comment by zxynxb** [comment]
ill make it on canva  and okiii

**Comment by Zain-ul-din** [comment]
good luck then i'll design banner on figma and also invite you there

**Comment by zxynxb** [comment]
OKIIII ill add when i turn on laptop tho

**Comment by Zain-ul-din** [comment]
hmm

**Comment by Zain-ul-din** [comment]
lmk when you'll finish with logo design then I'll start making issue template for the org.

**Comment by zxynxb** [comment]
okiii i asked my aunt she's a graphic designer :)
and im also making a readme md for the organization

**Comment by Zain-ul-din** [comment]
WOW!

**Comment by Zain-ul-din** [comment]
Also ask if she can manage to make ad like this it would be helpful for us to advertise this on LGU Timetable. It is not important for now cuz I think official's are going to acquire my project so can't say anything yet

![image](https://github.com/zxynxb/e-commerce-management-system/assets/78583049/669ae97e-d412-4015-83dd-e366a40578d0)

**Comment by zxynxb** [comment]
okay will ask and got the logo too but i think i need some more details and ill add them personally

**Comment by Zain-ul-din** [comment]
show me how it's looking.

**Comment by zxynxb** [comment]
![IMG-20240526-WA0011](https://github.com/zxynxb/e-commerce-management-system/assets/158732374/8a047240-4952-4422-b72e-b56d6f0309d5)

hows this

**Comment by zxynxb** [comment]
lmk if u want any changes

**Comment by Zain-ul-din** [comment]
Looking cool do you not think we need to change color.

**Comment by zxynxb** [comment]
any idea on which color should we do 
like hex code

**Comment by Zain-ul-din** [comment]
I was going to make a fork of this project in LGUCC and I think let me see the code how she did it I saw [this](https://github.com/zxynxb/e-commerce-management-system/blob/main/main.cpp#L100) funny thing there 😂are you working on this anymore or working on OO version one as you told me.

**Comment by zxynxb** [comment]
yes im working on a OOP version of this but it'll take time because im more focused on web development projects rn

also yes there are millions of things wrong with the code which i fixed in another version but its incomplete :)

**Comment by Zain-ul-din** [comment]
can you send me SVG format of logo so I can try diff colors on it and which theme to choose? dark/light

**Comment by Zain-ul-din** [comment]
> yes im working on a OOP version of this but it'll take time because im more focused on web development projects rn
> 
> also yes there are millions of things wrong with the code which i fixed in another version but its incomplete :)

this is going to be your semester proj? lmk if need help I worked at Game District as Game Developer and you know OOP is made for only games.

**Comment by zxynxb** [comment]
> > yes im working on a OOP version of this but it'll take time because im more focused on web development projects rn
> > also yes there are millions of things wrong with the code which i fixed in another version but its incomplete :)
> 
> this is going to be your semester proj? lmk if need help I worked at Game District as Game Developer and you know OOP is made for only games.

this was my first semesters semester project of PF 
i was planning to recreate this in OOP but im doing semester project in a group this semester so I'll recreate the new updated anf much more easier version of this in OOP probably alot time later 
also adding new features because I didn't remember that semester

**Comment by Zain-ul-din** [comment]
> can you send me SVG format of logo so I can try diff colors on it and which theme to choose? dark/light

.

**Comment by zxynxb** [comment]
let me ask
